Added ability to select backend at run time

diff --git a/bin/sdl_make_tracklooper b/bin/sdl_make_tracklooper
--- a/bin/sdl_make_tracklooper
+++ b/bin/sdl_make_tracklooper
@@ -26,14 +26,15 @@ usage()
   echo "  -p    primitive object ntuple   (With extra variables related to primitive objects)"
   echo "  -3    do T3T3 extensions        (-e turned on if not specified)"
   echo "  -N    neural networks           (Toggle LST neural networks)"
-  echo "  -C    cpu backend               (Run code on CPU, serially)"
+  echo "  -G    gpu backend               (Compile only for GPU, takes priority over -C)"
+  echo "  -C    cpu backend               (Compile only for CPU)"
   echo "  -2    no pLS duplicate cleaning (Don't perform the pLS duplicate cleaning step)"
   echo
   exit
 }
 
 # Parsing command-line opts
-while getopts ":cxgsmdp3NC2eh" OPTION; do
+while getopts ":cxgsmdp3NGC2eh" OPTION; do
   case $OPTION in
     c) MAKECACHE=true;;
     s) SHOWLOG=true;;
@@ -42,7 +43,8 @@ while getopts ":cxgsmdp3NC2eh" OPTION; do
     p) PRIMITIVE=true;;
     3) T3T3EXTENSION=true;;
     N) DONTUSENN=true;;
-    C) CPUBACKEND=true;;
+    G) ONLYGPUBACKEND=true;;
+    C) ONLYCPUBACKEND=true;;
     2) NOPLSDUPCLEAN=true;;
     h) usage;;
     :) usage;;
@@ -57,8 +59,12 @@ if [ -z ${MAKECUTVALUES} ]; then MAKECUTVALUES=false; fi
 if [ -z ${PRIMITIVE} ]; then PRIMITIVE=false; fi
 if [ -z ${T3T3EXTENSION} ]; then T3T3EXTENSION=false; fi
 if [ -z ${DONTUSENN} ]; then DONTUSENN=false; fi
-if [ -z ${CPUBACKEND} ]; then CPUBACKEND=false; fi
+if [ -z ${ONLYGPUBACKEND} ]; then ONLYGPUBACKEND=false; fi
+if [ -z ${ONLYCPUBACKEND} ]; then ONLYCPUBACKEND=false; fi
 if [ -z ${NOPLSDUPCLEAN} ]; then NOPLSDUPCLEAN=false; fi
+
+# If using both -G and -C, -G takes priority
+if [ "${ONLYGPUBACKEND}" == true ]; then ONLYCPUBACKEND=false; fi
 
 # Shift away the parsed options
 shift $(($OPTIND - 1))
@@ -83,7 +89,8 @@ echo "  MAKECUTVALUES     : ${MAKECUTVALUES}"                 | tee -a ${LOG}
 echo "  PRIMITIVE         : ${PRIMITIVE}"                     | tee -a ${LOG}
 echo "  T3T3EXTENSION     : ${T3T3EXTENSION}"                 | tee -a ${LOG}
 echo "  DONTUSENN         : ${DONTUSENN}"                     | tee -a ${LOG}
-echo "  CPUBACKEND        : ${CPUBACKEND}"                    | tee -a ${LOG}
+echo "  ONLYGPUBACKEND    : ${ONLYGPUBACKEND}"                | tee -a ${LOG}
+echo "  ONLYCPUBACKEND    : ${ONLYCPUBACKEND}"                | tee -a ${LOG}
 echo "  NOPLSDUPCLEAN     : ${NOPLSDUPCLEAN}"                 | tee -a ${LOG}
 echo ""                                                       | tee -a ${LOG}
 echo "  (cf. Run > sh $(basename $0) -h to see all options)"  | tee -a ${LOG}
@@ -132,7 +139,9 @@ else
 fi
 
 BACKENDOPT=
-if $CPUBACKEND; then
+if [ "$ONLYGPUBACKEND" == true ]; then
+    BACKENDOPT="BACKEND=gpu"
+elif [ "$ONLYCPUBACKEND" == true ]; then
     BACKENDOPT="BACKEND=cpu"
 fi
 
@@ -158,10 +167,15 @@ else
     (cd SDL && make clean && make ${T3T3EXTENSIONOPT} ${T5CUTOPT} ${BACKENDOPT} ${NOPLSDUPCLEANOPT} -j 32 ${MAKETARGET} && cd -) >> ${LOG} 2>&1
 fi
 
-if [ ! -f SDL/libsdl.so ]; then
-    echo "ERROR: SDL/libsdl.so failed to compile!" | tee -a ${LOG}
-    echo "See ${LOG} file for more detail..." | tee -a ${LOG}
-    exit 1
+if [[ "$BACKENDOPT" != *"gpu"* ]] && [ ! -f SDL/libsdl_cpu.so ]; then
+  echo "ERROR: libsdl_cpu.so failed to compile!" | tee -a ${LOG}
+  echo "See ${LOG} file for more detail..." | tee -a ${LOG}
+  exit 1
+elif [[ "$BACKENDOPT" != *"cpu"* ]] && [ ! -f SDL/libsdl_gpu.so ]; then
+  echo "ERROR: libsdl_gpu.so failed to compile!" | tee -a ${LOG}
+  echo "See ${LOG} file for more detail..." | tee -a ${LOG}
+  echo $BACKENDOPT
+  exit 1
 fi
 
 echo "" >> ${LOG}
diff --git a/bin/sdl_run b/bin/sdl_run
--- a/bin/sdl_run
+++ b/bin/sdl_run
@@ -24,6 +24,7 @@ usage()
   echo "  -n    number of events        (Number of events to run over)"
   echo "  -t    tag for this run        (Tag for this run)"
   echo "  -d    delete previous output  (Delete the previous outputs and re-run)"
+  echo "  -b    backend                 (Select between GPU and CPU backend)"
   echo
   exit
 }
@@ -31,12 +32,13 @@ usage()
 DELETE=false
 
 # Parsing command-line opts
-while getopts ":f:s:n:t:dh" OPTION; do
+while getopts ":f:s:n:t:b:dh" OPTION; do
   case $OPTION in
     f) FLAGS=${OPTARG};;
     s) SAMPLE=${OPTARG};;
     n) NEVENTS=${OPTARG};;
     t) TAG=${OPTARG};;
+    b) BACKEND=${OPTARG};;
     d) DELETE=true;;
     h) usage;;
     :) usage;;
@@ -44,13 +46,44 @@ while getopts ":f:s:n:t:dh" OPTION; do
 done
 
 # If the command line options are not provided set it to default value of false
-if [ -z ${FLAGS} ]; then usage; fi
+if [ -z ${FLAGS} ]; then PRECOMPILED=true; else PRECOMPILED=false; fi
 if [ -z ${SAMPLE} ]; then usage; fi
 if [ -z ${NEVENTS} ]; then NEVENTS=-1; fi
 if [ -z ${TAG} ]; then usage; fi
 
+# If it will not be compiled, then make sure that it was precompiled
+if ${PRECOMPILED}; then
+  if [ ! -f ${TRACKLOOPERDIR}/bin/sdl ] || ( [ ! -f ${TRACKLOOPERDIR}/SDL/libsdl_gpu.so ] && [ ! -f ${TRACKLOOPERDIR}/SDL/libsdl_cpu.so ] ); then
+    echo "SDL library or binary has not been compiled. Please use -f flag."
+    usage
+  fi
+fi
+
+# If a backend is specified then make sure that corresponding library exists
+# and set the environment variable to preload it.
+if [ -z ${BACKEND} ]; then
+  PRELOAD=
+elif [ "${BACKEND}" == "gpu" ]; then
+  if ([ ${PRECOMPILED} != true ] && [[ "${FLAGS}" == *"C"* ]]) ||
+       ([ ${PRECOMPILED} == true ] && ([ ! -f ${TRACKLOOPERDIR}/SDL/libsdl_gpu.so ] || [ ! -f ${TRACKLOOPERDIR}/SDL/gpu/libsdl.so ])); then
+    echo "Error: GPU library was not compiled."
+    exit 1
+  fi
+  PRELOAD="LD_PRELOAD=${TRACKLOOPERDIR}/SDL/gpu/libsdl.so"
+elif [ "${BACKEND}" == "cpu" ]; then
+  if ([ ${PRECOMPILED} != true ] && [[ "${FLAGS}" == *"G"* ]]) ||
+       ([ ${PRECOMPILED} == true ] && ([ ! -f ${TRACKLOOPERDIR}/SDL/libsdl_cpu.so ] || [ ! -f ${TRACKLOOPERDIR}/SDL/cpu/libsdl.so ])); then
+    echo "Error: CPU library was not compiled."
+    exit 1
+  fi
+  PRELOAD="LD_PRELOAD=${TRACKLOOPERDIR}/SDL/cpu/libsdl.so"
+else
+  echo "Error: backend options are gpu or cpu."
+  exit 1
+fi
+
 # Check that the FLAGS start with "-" character
-if [[ ${FLAGS:0:1} == "-" ]]; then
+if [[ ${PRECOMPILED} == true ]] || [[ ${FLAGS:0:1} == "-" ]]; then
     :
 else
     echo "ERROR:"
@@ -118,10 +151,12 @@ fi
 mkdir -p ${LSTOUTPUTDIR}
 
 rm -f ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log
-echo "Compiling code..."
-sdl_make_tracklooper ${FLAGS} >> ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log
+if [[ ${PRECOMPILED} != true ]]; then
+  echo "Compiling code..."
+  sdl_make_tracklooper ${FLAGS} >> ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log
+fi
 echo "Running LST code..."
-sdl -i ${SAMPLE} -o ${LSTOUTPUTDIR}/${JOBTAG}__LSTNtuple.root -n ${NEVENTS} >> ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log 2>&1 || { echo 'ERROR: sdl command failed!' ; exit 1; }
+eval "${PRELOAD} sdl -i ${SAMPLE} -o ${LSTOUTPUTDIR}/${JOBTAG}__LSTNtuple.root -n ${NEVENTS} >> ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log 2>&1" || { echo 'ERROR: sdl command failed!' ; exit 1; }
 echo "Creating performance histograms..."
 createPerfNumDenHists -i ${LSTOUTPUTDIR}/${JOBTAG}__LSTNtuple.root -o ${LSTOUTPUTDIR}/${JOBTAG}__LSTNumDen.root >> ${LSTOUTPUTDIR}/${JOBTAG}__LSTRun.log 2>&1 || { echo 'ERROR: createPerfNumDenHists command failed!' ; exit 1; }
 echo "Creating plots..."
