Add CPU backend timing option

diff --git a/efficiency/bin/sdl_timing b/efficiency/bin/sdl_timing
--- a/efficiency/bin/sdl_timing
+++ b/efficiency/bin/sdl_timing
@@ -5,37 +5,51 @@ run_gpu()
     version=$1
     sample=$2
     nevents=$3
-    shift
-    shift
-    shift
-    # GPU unified
+    shift 3
+    # GPU backend
     sdl_make_tracklooper -m $*
-    sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s1.root -v 1 -w 0 -i ${sample} | tee -a timing_temp.txt
-    sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s2.root -v 1 -w 0 -s 2 -i ${sample} | tee -a timing_temp.txt
-    sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s4.root -v 1 -w 0 -s 4 -i ${sample} | tee -a timing_temp.txt
-    sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s6.root -v 1 -w 0 -s 6 -i ${sample} | tee -a timing_temp.txt
-    sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s8.root -v 1 -w 0 -s 8 -i ${sample} | tee -a timing_temp.txt
+    for s_value in 1 2 4 6 8; do
+        sdl -n ${NEVENTS} -o ${OUTDIR}/gpu_${version}_s${s_value}.root -v 1 -w 0 -s ${s_value} -i ${sample} | tee -a timing_temp.txt
+    done
+}
+
+run_cpu()
+{
+    version=$1
+    sample=$2
+    nevents=$3
+    shift 3
+    # CPU backend
+    sdl_make_tracklooper -mC $*
+    for s_value in 1 4 16 32 64; do
+        sdl -n ${NEVENTS} -o ${OUTDIR}/cpu_${version}_s${s_value}.root -v 1 -w 0 -s ${s_value} -i ${sample} | tee -a timing_temp.txt
+    done
 }
 
 run_timing_test_usage()
 {
     echo "ERROR - Usage:"
     echo
-    echo "      sh $(basename $0) SAMPLETYPE [SPECIFICGPUVERISON] [NEVENTS]"
+    echo "      sh $(basename $0) [-b BACKEND] SAMPLETYPE [SPECIFICGPUVERISON] [NEVENTS]"
+    echo
+    echo "Options:"
+    echo "   -b BACKEND                         cpu or gpu (default is gpu)"
     echo
     echo "Arguments:"
-    echo "   SAMPLETYPE                          muonGun, PU200, or pionGun"
-    echo "   SPECIFICGPUVERSION (optional)       Run only one of the cache, etc."
-    echo "                                       If nothing provided, then it checks all possible tests."
-    echo "   NEVENTS            (optional)       200, 10000, -1, etc."
+    echo "   SAMPLETYPE                         muonGun, PU200, or pionGun"
+    echo "   SPECIFICGPUVERSION (optional)      Run only one of the cache, etc."
+    echo "                                      If nothing provided, then it checks all possible tests."
+    echo "   NEVENTS           (optional)       200, 10000, -1, etc."
     echo ""
     exit
 }
 
 # Parsing command-line opts
-while getopts ":h" OPTION; do
+BACKEND="gpu"  # Default to GPU if no backend specified
+while getopts ":hb:" OPTION; do
   case $OPTION in
     h) usage;;
+    b) BACKEND=$OPTARG;;
     :) usage;;
   esac
 done
@@ -58,13 +72,21 @@ SPECIFICGPUVERSION=${2}
 
 if [ -z ${3} ]; then
     NEVENTS=200 # If no number of events provided, validate on first 200 events
-    if [[ ${SAMPLE} == *"PU200"* ]]; then
-        NEVENTS=200 # If PU200 then run 30 events
-    fi
 else
     NEVENTS=${3} # If provided set the NEVENTS
 fi
 
+# Decide which function to run
+if [ "$BACKEND" == "gpu" ]; then
+    run_func=run_gpu
+elif [ "$BACKEND" == "cpu" ]; then
+    run_func=run_cpu
+else
+    echo "Invalid backend specified."
+    exit 1
+fi
+
+# Check if there are any uncommited changes in the repo
 pushd ${TRACKLOOPERDIR}
 GITHASH=$(git rev-parse --short HEAD)
 DIRTY=""
@@ -98,19 +120,17 @@ echo "  SPECIFICGPUVERSION   : all configurations"
 fi
 echo ""
 
-## Delete old run
+# Delete old run
 rm -rf ${OUTDIR}
 mkdir -p ${OUTDIR}
 rm -f timing_temp.txt
 
-# Run different GPU configurations
-if [ -z ${SPECIFICGPUVERSION} ] || [[ "${SPECIFICGPUVERSION}" == "explicit" ]]; then
-    run_gpu explicit ${SAMPLE} ${NEVENTS} -8 -e
-    :
+# Run different configurations
+if [ -z "${SPECIFICGPUVERSION}" ] || [[ "${SPECIFICGPUVERSION}" == "explicit" ]]; then
+    $run_func explicit "${SAMPLE}" "${NEVENTS}"
 fi
-if [ -z ${SPECIFICGPUVERSION} ] || [[ "${SPECIFICGPUVERSION}" == "explicit_cache" ]]; then
-     run_gpu explicit_cache ${SAMPLE} ${NEVENTS} -c -8 -e
-    :
+if [ -z "${SPECIFICGPUVERSION}" ] || [[ "${SPECIFICGPUVERSION}" == "explicit_cache" ]]; then
+    $run_func explicit_cache "${SAMPLE}" "${NEVENTS}" -c
 fi
 
 echo "Total Timing Summary"
